### ISSUE TITLE
Update your code

### ISSUE THREAD

**Issue by Stepandanci** [Turcanuse/junior_test_task#1]
You started writing a test task well.
Here is a list of tasks for you to update your code.

0. Open a new pull request from `dev` branch to `master` for review and do not merge it yet.

1. We recommend you to read the Ruby Style Guide and update your code.
- https://rubystyle.guide

2. Use Nokogiri and CSS selectors instead of Xpath.
- https://nokogiri.org/
- https://www.w3schools.com/cssref/css_selectors.asp

3 Separate class Account and class Transactions.
- Move class Account to file `account.rb`
- Move class Transaction to file `transaction.rb`

4 Update code structure
- Create a file Fibank.rb
- Move code from `scrape.rb` to one class `Fibank`
- Unite code from `scrape.rb` to methods.

Here is an example structure:

```ruby
class Fibank

  def initialize

  end

  def execute
    connect
    fetch_accounts
    fetch_transactions
    show_result
  end

  def connect
    # here you log in to bank
  end

  def fetch_accounts
    # fetch html data using nokogiri
    html = Nokogiri::HTML(browser.html)

    parse_accounts(html)
  end

  def fetch_transactions
    accounts.each do |account|
      # go to transactions HTML
      # add transactions to account
      parse_transactions(account, html)
    end
  end

  def parse_accounts(html)

  end

  def parse_transactions(account, html)

  end
end

Fibank.execute
```

Good Luck!

**Comment by Stepandanci** [comment]
If you have any questions, ask me in this issue.

**Comment by Turcanuse** [comment]
Thank you for pointing me in the right direction. However i have one question.  I seem to circle around this one. The Nokogiri object i am creating, doesn't retrieve the full html. I understand why, due to data being loaded async. So i'm trying to get the XML, this also seems to be quite difficult as I looked through all XML files and I get same error,  "401  An Authentication object was not found in the SecurityContext "
Trying to work around with  "execute_script method" , no luck.

Kind Regads

![Captură de ecran din 2019-10-29 la 5 40 26 p m](https://user-images.githubusercontent.com/57009526/67798973-32bb9e00-fa8d-11e9-9165-d6f7cf20ccef.png)
![Captură de ecran din 2019-10-29 la 5 39 34 p m](https://user-images.githubusercontent.com/57009526/67799000-3f3ff680-fa8d-11e9-94e2-15e2b0594d88.png)

**Comment by Stepandanci** [comment]
No need to take full HTML
Use `Nokogiri::HTML.fragment` to extract page fragment with accounts data

```ruby
accounts_html = Nokogiri::HTML.fragment(browser.div(class: "dashboard-main").html)
```

**Comment by Stepandanci** [comment]
We recommend you to use `Pry` runtime developer console to handle your code.
Read about `Pry` here https://github.com/pry/pry

Run your code `ruby example.rb`

use method `binding.pry`

```ruby
  def execute
    binding.pry # You stop at this line and can debug your code

    your code
  end
```

**Comment by Turcanuse** [comment]
Thank you for the tips. Will do so.

**Comment by Turcanuse** [comment]
Hello, 
Can you give me a hint on how to interlock the classes,  I seem to circle around.
Thank you

**Comment by Turcanuse** [comment]
Disregard my last comment. I will rewrite everything from Fibank to a module.

**Comment by Stepandanci** [comment]
0. Try to open a `Pull request` and do not merge it. I will give you more tips on your code.
1. No need to use a **Database** in your test task.  Remove `require 'sqlite3'`
2. Save accounts and transactions data in **JSON** 
3. In `BankAccount` class remove default params in `initialize`
```ruby
def initialize(balance, name, currency, nature)
```
4.  no need to use `@@` use simple `@` for `name`.
5. remove `puts ` in code after debugging. 
6. No need to inherit account class to transaction class.
7. Move bank URL to constant  `LOGIN_URL = "https://my.fibank.bg/oauth2-server/login?client_id=E_BANK"`

**Comment by Stepandanci** [comment]
1. Remove duplicated components.
2. Use cycles `each` `for` `while` in code.
3. Do not `hardcode` data in your program, make in universal.

**Comment by Turcanuse** [comment]
Hello,

I think I solved it, in the dev_2 branch.
Thank you for your help.

Kind regards

**Comment by Stepandanci** [comment]
You incorrectly completed your test task.

class Account and Transaction must be created by this structure

file `account.rb`

```ruby
class Account
  attr_reader :balance, :name, :currency, :nature

  def initialize(name, balance, currency, nature)
    @name         = name
    @balance      = balance
    @currency     = currency
    @nature       = nature
    @transactions = []
  end
end
```

`transactions.rb`

```ruby
class Transaction
  attr_reader :balance, :name, :currency, :nature

  def initialize(date, description, amount, account)
    @date         = date
    @description  = description
    @amount       = amount
    @account_name = account.name
    @currency     = account.currency
  end
end
```

**Comment by Stepandanci** [comment]
1. Read about iterators in Ruby.  
- https://www.tutorialspoint.com/ruby/ruby_iterators.htm  
- https://www.rubyguides.com/ruby-tutorial/loops/

2. Remove wrong code
```
      account_1 = []
      account_2 = []
      account_3 = []
```
3. Code must be universal do not harcode data in code
```
 @tran_4.include?('BG35FINV91502003939180')
```
4. Check current time in code  
```ruby
 Time.now.strftime("%d/%m/%Y")
```
remove it
```
date_2 = "01/10/2019"
```

**Comment by Stepandanci** [comment]
in `fetch_accounts`
create  variable `@accounts`

in `fetch_transactions` use `iterator` `each`

```ruby
@accounts.each do |account|
```

add transactions to this `account`

```ruby
account.transactions << transactions
```

**Comment by Stepandanci** [comment]
Read about Ruby.
Do not rush to complete the task without the right theoretical knowledge.

**Comment by Turcanuse** [comment]
I used the iterators and fixed the date. 
I have one question, how should i extract the raw html from the <i> tag so that I could set the "-/+"?
Thank you.

Kind regards,
Sergiu

**Comment by Stepandanci** [comment]
Read about CSS selectors here https://www.w3schools.com/cssref/css_selectors.asp

**Comment by Stepandanci** [comment]
Please update your code 

https://github.com/Turcanuse/junior_test_task/pull/3/files#r343257186
https://github.com/Turcanuse/junior_test_task/pull/3/files#r343261627

**Comment by Turcanuse** [comment]
Will do so, for sure. Thank you for  your guidance.

Kind regards,
Sergiu

**Comment by Turcanuse** [comment]
![Captură de ecran din 2019-11-07 la 9 38 34 p m](https://user-images.githubusercontent.com/57009526/68422363-b6217180-01a8-11ea-9e3a-b9786d3e831b.png)
![Captură de ecran din 2019-11-07 la 9 35 39 p m](https://user-images.githubusercontent.com/57009526/68422379-c0437000-01a8-11ea-8d6e-c234d86d4896.png)

![Captură de ecran din 2019-11-07 la 9 55 01 p m](https://user-images.githubusercontent.com/57009526/68422651-495aa700-01a9-11ea-8abd-2e8c6184d16d.png)

How would you suggest to access the nested i ?
Thanks.

**Comment by Stepandanci** [comment]
Use `binding.pry` before line 100. For debug `click` method and find the correct `watir` selector.  
Click to checkbox without `.child`

**Comment by Stepandanci** [comment]
Please, read again your test task.

Create a method `to_json` that will combine account data in 1 hash.
It will be required to write a test for your code with `RSpec`.

example structure: 

```json
{
    "accounts": [
    {
        "name": "account1",
        "balance": 300.22,
        "currency": "MDL",
        "nature": "checking"
    }]
}
```

Do the same for the transaction class.

```json
{
  "date": "2015-01-15T08:18:26Z",
  "description": "bought food",
  "amount": -20.31,
  "currency": "MDL",
  "account_name": "account1"
}
```

Pay attention to this part.

7. Extend your script in such a way that the stored accounts contain a list of their Transactions.

Example of output:

```json

{
    "accounts": [
    {
        "name": "account1",
        "balance": 300.22,
        "currency": "MDL",
        "description": "My checking account",
        "transactions": [
        {
            "date": "2015-01-15T08:18:26Z",
            "description": "bought food",
            "amount": -20.31,
            "currency": "MDL",
            "account_name": "account1"
        }]
    }]
}

```

**Comment by Turcanuse** [comment]
Ok. I will do my best.

Thank you.

**Comment by Turcanuse** [comment]
Hello,

Can you take a look at the last update?
Thank you in advance.

Kind regards,
Sergiu

**Comment by Stepandanci** [comment]
No changes was found.  
Last commit was on Nov 6, 2019.
Push your code to dev2 branch.

**Comment by Turcanuse** [comment]
Done.

Kind regards,
Sergiu

**Comment by Stepandanci** [comment]
Update your code structure.

1. fetch_transactions
https://github.com/Turcanuse/junior_test_task/pull/3/files#r344873688

2.to_hash
https://github.com/Turcanuse/junior_test_task/pull/3/files#r344874820

**Comment by Turcanuse** [comment]
Hello,

Can you take a look at my last pull?
Thank you in advance.

Kind regards,
Sergiu

**Comment by Turcanuse** [comment]
The RSpec should be for the to_hash methods from account and transaction class, to check against the actual values? Or for all  class methods from each file?


Kind regards,
Sergiu

**Comment by Stepandanci** [comment]
Update my last conversations and go to this Issue for **Rspec** https://github.com/Turcanuse/junior_test_task/issues/5
